[logger]
enable = true
level = "debug"

[server]
address = "[::]:2747"
pid-file = ""

[database]
run-seeder = false
seeder-path = "seeder"

[security]
authentication-fail-delay-ms = 100

[security.session]
token-prefix = "wj:"
token-length = 64
duration-session-minutes = 30
duration-login-minutes = 5

[security.mfa]
recovery-code-count = 4
recovery-code-length = 8
time-step = 30
time-skew = 1

[domain]
main = "wikijump.com"
files = "wjfiles.com"

[job]
workers = 2
max-attempts = 3
delay-ms = 5
min-delay-poll-secs = 10  # 10 seconds
max-delay-poll-secs = 360  # 6 minutes
prune-session-secs = 600  # 5 minutes
prune-text-secs = 86400  # 1 day
name-change-refill-secs = 86400  # 1 day
lift-expired-punishments-secs = 86400  # 1 day

[locale]
path = "/opt/locales"

[ftml]
render-timeout-ms = 2000
rerender-skip = [
    { job-depth = 1, last-update-ms = 100 },
    { job-depth = 10, last-update-ms = 1500 },
    { job-depth = 50, last-update-ms = 0 },
]
[ftml.layout]
messages = "wikijump"
default-page = "wikidot"

[special-pages]
special-prefix = "_"
template = "_template"
missing = "_404"
private = "_public"
banned = "_ban"

[user]
default-name-changes = 2
maximum-name-changes = 3
minimum-name-bytes = 3
refill-name-change-days = 90

[file]
presigned-path-length = 32
presigned-expiration-minutes = 5
maximum-blob-size-kb = 1048576  # 1 GiB
maximum-avatar-size-kb = 100  # 100 KiB

[message]
maximum-subject-bytes = 128
maximum-body-bytes = 200000
maximum-recipients = 6
