language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

stages:
  - format
  - clippy
  - test
  - bin
  - doc

before_script:
  - rustup component add rustfmt

jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true
  include:
    - stage: format
      script:
        - rustfmt --edition=2018 src/lib.rs --check
        - rustfmt --edition=2018 ftml-rpc/src/lib.rs --check
        - rustfmt --edition=2018 ftml-rpc/src/main.rs --check
        - rustfmt --edition=2018 examples/ftml/main.rs --check
    - stage: clippy
      script:
        - rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu
        - rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu
        - cargo +nightly-2020-01-02 clippy
        - cd ftml-rpc
        - cargo +nightly-2020-01-02 clippy
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      os:
        - linux
        - osx
        - windows
      script:
        - cargo build --verbose --release
        - cargo test --verbose --release -- --nocapture
        - cd ftml-rpc
        - cargo build --verbose --release
        - cargo test --verbose --release -- --nocapture
    - stage: bin
      script:
        - cargo build --verbose --release --example ftml
    - stage: doc
      script:
        - cargo doc --verbose

notifications:
  email:
    on_success: change
    on_failure: always
