language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

cache: cargo

before_script:
  - rustup component add rustfmt

stages:
  - format
  - clippy
  - test
  - bin
  - doc

jobs:
  include:
    - stage: format
      script:
        - rustfmt src/lib.rs --check
        - rustfmt examples/ftml/main.rs --check
    - stage: clippy
      script:
        - rustup component add clippy --toolchain nightly-2019-09-25-x86_64-unknown-linux-gnu
        - cargo +nightly-2019-09-25 clippy
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      os:
        - linux
        - osx
        - windows
      script:
        - cargo build --verbose
        - cargo test --verbose -- --nocapture
    - stage: bin
      script:
        - cargo build --verbose --example ftml
    - stage: doc
      script:
        - cargo doc --verbose

notifications:
  email:
    on_success: change
    on_failure: always
