[package]
name = "ftml"
description = "Foundation Text Markup Language - a library to convert Wikidot code to HTML"
repository = "https://github.com/Nu-SCPTheme/ftml"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["wikidot", "ftml", "parsing", "rendering", "html"]
categories = []
exclude = [".gitignore", ".travis.yml"]

version = "0.2.19"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml version

[badges]
travis-ci = { repository = "Nu-SCPTheme/ftml", branch = "master" }

[lib]
name = "ftml"

[dependencies]
lazy_static = "1"
logos = "0.11"
regex = "1"
slog = "2.5"
str-macro = "0.1"
strum = "0.18"
strum_macros = "0.18"
thiserror = "1"
tinyvec = "1"

[dev-dependencies]
sloggers = "1"
