[package]
name = "ftml"
description = "Foundation Text Markup Language - a library to convert Wikidot code to HTML"
repository = "https://github.com/Nu-SCPTheme/ftml"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["wikidot", "ftml", "parsing", "rendering", "html"]
categories = []
exclude = [".gitignore", ".travis.yml"]

version = "0.2.19"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml version

[badges]
travis-ci = { repository = "Nu-SCPTheme/ftml", branch = "master" }

[workspace]
members = [
    ".",
    "ftml-bin",
]

[lib]
name = "ftml"

[dependencies]
chrono = "0.4"
either = "1.5"
lazy_static = "1"
log = "0.4"
percent-encoding = "2"
pest = "2.1"
pest_derive = "2.1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
str-macro = "0.1"
thiserror = "1"
tinyvec = "0.3"
