name: "[client monorepo] TypeScript"

on:
  push:
    paths:
      - "client/**"
      - "ftml/test/*"
      - ".github/workflows/client.yaml"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Dependency Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            client/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('client/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: cd client && npm ci

      - name: Test
        run: cd client && npm test

      - name: Validate
        run: cd client && npm run validate

      - name: Export Coverage
        uses: codecov/codecov-action@v1
        with:
          directory: client/coverage
          flags: clientmonorepo
