name: '[backend] Docker build Framerail (dev)'

on:
  pull_request:
    paths:
      - 'framerail/**'
      - 'install/dev/digitalocean/web/Dockerfile'
      - '.github/workflows/docker-build-web.dev.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -f install/dev/digitalocean/web/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
