name: '[backend] Docker push Nginx'

on:
  push:
    branches:
      - develop
    paths:
      - 'web/web/**'
      - 'web/package.json'
      - 'web/tsconfig.json'
      - 'install/aws/dev/docker/nginx/**'
      - '.github/workflows/docker-build-push-nginx.dev.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DOCKER_PUSH_KEY }}
          aws-secret-access-key: ${{ secrets.DOCKER_PUSH_SECRET }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wikijump-dev/nginx
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -ex
          docker build -f install/aws/dev/docker/nginx/Dockerfile --build-arg WIKIJUMP_REPO_BRANCH=${GITHUB_REF##*/} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:develop .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition wikijump-dev-ec2 --query taskDefinition > task-definition.json
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nginx
          image: ${{ steps.build-image.outputs.image }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: wikijump-dev-svc
          cluster: wikijump-dev
          wait-for-service-stability: true
