name: '[backend] Docker build Nginx (dev)'

on:
  push:
    branches-ignore:
      - develop
      - prod
    paths:
      - 'web/web/**'
      - 'web/package.json'
      - 'web/tsconfig.json'
      - 'install/files/nginx.conf'
      - 'install/aws/dev/docker/nginx/Dockerfile'
      - '.github/workflows/docker-build-nginx.dev.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -f install/aws/dev/docker/nginx/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
